version: 2

builds:
  - id: think
    binary: think
    main: ./cmd/think
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

  - id: thought
    binary: thought
    main: ./cmd/thought
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      thinkingscript_{{ .Version }}_{{ .Os }}_{{ .Arch }}
